<?php

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\node\Entity\Node;
use Drupal\taxonomy\Entity\Term;


function ssp_import_node_presave($node){
	// Reset the sensitivity each time before we save
	$node->field_sensitivity->value = '';
	$node->field_is_sensitive->value = 0;
			
	// First, species which are not exploited, are managed or have exploitation unknown cannot be sensitive
	if($node->field_exploitation_extent->value == 'none' || 
	   $node->field_exploitation_extent->value == 'unknown' ||
	   $node->field_exploitation_extent->value == 'managed') {	
		return;
	}
	
	// Deal with the close relatives separately
	if($node->field_exploitation_extent->value != 'uncertain') {	
		
		// Individuals are permanently removed and killed
		if($node->field_targeted_demographics->value == 'harmful' || $node->field_targeted_demographics->value == 'harmful_immature') {
			
			// It is sensitive if there is a vulnerable population
			if($node->field_population_vulnerability->value == 'vulnerable') { 
				$node->field_sensitivity->value = 'rare';
				$node->field_is_sensitive->value = 1;
			}
			
			// Otherwise, if the exploitation is significant...
			else if($node->field_exploitation_extent->value == 'significant') {
				
				// Check the regeneration potential value, if it's good then flag as sensitive
				if($node->field_regeneration_potential->value == 'poor') {
					$node->field_sensitivity->value = 'exploited';
					$node->field_is_sensitive->value = 1;
				}			
			}
		}
	}
	
	// Utilisation is having a significant effect on a close relative with similar life traits
	else {		
		
		// Double check that the relative is actually a sensitive species
		$relative_nid = $node->field_similar_species->getValue()[0]['target_id'];
		$relative = Node::load($relative_nid);
		// if($relative->field_is_sensitive->value > 0) { I'm taking this out after Tilla's presentation
		if($relative->field_targeted_demographics->value == 'harmful' || $node->field_targeted_demographics->value == 'harmful_immature') {
		
			// Does this (the original) species have a vulnerable population
			if($node->field_population_vulnerability->value == 'vulnerable') { 
				$node->field_sensitivity->value = 'relative';
				$node->field_is_sensitive->value = 1;
			}
		}	
	}
}