<?php

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\node\Entity\Node;
use Drupal\taxonomy\Entity\Term;


function ssp_import_node_presave($node){
	// Reset the sensitivity each time before we save
	$node->field_sensitivity->value = '';
	$node->field_is_sensitive->value = 0;
			
	
	// Deal with the close relatives separately
	if($node->field_exploitation_extent->value != 'uncertain') {	
		
		// Individuals are permanently removed and killed
		if($node->field_targeted_demographics->value == 'harmful') {
			
			// It is sensitive if there is a vulnerable population
			if($node->field_population_vulnerability->value == 'vulnerable') { 
				$node->field_sensitivity->value = 'rare';
				$node->field_is_sensitive->value = 1;
			}
			
			// Otherwise, if the exploitation is significant...
			else if(($node->field_exploitation_extent->value == 'significant')) {
				$node->field_sensitivity->value = 'exploited';
				$node->field_is_sensitive->value = 1;
			}
		}
	}
	
	// Utilisation is having a significant effect on a close relative with similar life traits
	else {		
		
		// Double check that the relative is actually a sensitive species
		$relative_nid = $node->field_similar_species->getValue()[0]['target_id'];
		$relative = Node::load($relative_nid);
		if($node->field_is_sensitive->value > 0) {
		
			// Does this species have a vulnerable population
			if($node->field_population_vulnerability->value == 'vulnerable') { 
				$node->field_sensitivity->value = 'relative';
				$node->field_is_sensitive->value = 1;
			}
		}	
	}
	
	// At this stage, if it's sensitive, we need to re-evaluate all of the ones that refer to it?
	//kpr($node->field_population_vulnerability);
	//kpr($node->field_population_vulnerability->value);
	//print('ok');
	//$node->field_population_vulnerability->value = 'exploited';
	//kpr($node->field_population_vulnerability);
	//kpr($node->field_population_vulnerability->value);
	//exit();
	//print_r(count($relative->field_sensitivity->getValue()));
	//exit();
}